sudo: required
services:
  - docker

before_install:
  - docker build -t gizzy444/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gizzy444/react-test npm test

after_success:
  - docker build -t gizzy444/multi-client ./client
  - docker build -t gizzy444/multi-nginx ./nginx
  - docker build -t gizzy444/multi-server ./server
  - docker build -t gizzy444/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push gizzy444/multi-client
  - docker push gizzy444/multi-nginx 
  - docker push gizzy444/multi-server
  - docker push gizzy444/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-931370272174
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY